[package]
name = "coff-linker"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
byteorder = "*"
clap = { version = "4.3.12", features = ["derive"] }
